image: ${DOCKER_DIND}

services:
- name: ${DOCKER_DIND}
  alias: dind
  command: ['--insecure-registry=registry.cea.com.br:5005']

stages: 
  - build_container
  - deploy


variables:
  OPENSHIFT_PROJECT: "cea-${CI_PROJECT_NAMESPACE}"
  GIT_SSL_NO_VERIFY: "1"
  #https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
  DOCKER_HOST: tcp://dind:2375
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""  
  # PROJECT_PATH: "$CI_PROJECT_DIR"


docker-build:
  stage: build_container
  before_script:
    - ls Dockerfile | xargs sed -i "s/ENVIRONMENT/homolog/g"
  script:
    - env
    - echo $CI_COMMIT_BRANCH
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_BRANCH .
    - docker push  $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_BRANCH
  only:
    - develop


docker-build-tags:
  stage: build_container
  before_script:
    - ls Dockerfile | xargs sed -i "s/ENVIRONMENT/production/g"
  script:
    - env
    - echo $CI_BUILD_TAG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_TAG .
    - docker push  $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_TAG
  only:
    - /^[0-9]+.[0-9]+.[0-9]+$/


homolog:
  stage: deploy
  image: "openshift/origin-cli"
  dependencies:
    - docker-build
  variables:
    CLUSTER: ocpvh1
  environment:
    name: homolog
    kubernetes:
      namespace: ${KUBE_NAMESPACE}
  before_script:
    - oc login --server=https://api.${CLUSTER}.cea.com.br:6443 --token=${OCP_TOKEN_HOM} --insecure-skip-tls-verify
    - chmod +x ./deploy.sh
  script:
    - ./deploy.sh ${CI_COMMIT_BRANCH}
  only:
    - develop


production:
  stage: deploy
  image: "openshift/origin-cli"
  dependencies:
    - docker-build
  variables:
    CLUSTER: ocpvp1
  environment:
    name: production
    kubernetes:
      namespace: ${KUBE_NAMESPACE}
  when: manual
  before_script:
    - oc login --server=https://api.${CLUSTER}.cea.com.br:6443 --token=${OCP_TOKEN_PRD} --insecure-skip-tls-verify  
    # - chmod +x ./deploy.sh
  script:
    - ./deploy.sh ${CI_BUILD_TAG}
  only:
    - /^[0-9]+.[0-9]+.[0-9]+$/
